regItem("end_soul_shard", "End Soul shard", 64);
regItem("mind_soul_shard", "Mind Soul shard", 64);
regItem("nether_soul_shard", "Nether Soul shard", 64);
regItem("peace_soul_shard", "Peace Soul shard", 64);
regItem("undeath_soul_shard", "Undeath Soul shard", 64);
regItem("water_soul_shard", "Water Soul shard", 64);
regItem("wild_soul_shard", "Wild Soul shard", 64);
regItem("will_soul_shard", "Will Soul shard", 64);
regItem("wither_soul_shard", "Wither Soul shard", 64);