talismans.regTalisman(["spell", "armor_of_pacifist", 1, 80000], "Armor of pacifist", "ru", function () {	});
talismans.regTalisman(["spell", "arrow_deflection", 6, 80000], "Arrow deflection", "ru", function () {	});
talismans.regTalisman(["spell", "arrow_throw", 0, 80000], "Arrow throw", "ru", function () {	});
talismans.regTalisman(["spell", "bind_ice_arrows", 1, 80000], "Bind ice arrows", "ru", function () {	});
talismans.regTalisman(["spell", "blade_of_grass", 9, 80000], "Blade of grass", "ru", function () {	});
talismans.regTalisman(["spell", "blazing_palm", 5, 80000], "Blazing palm", "ru", function () {	});
talismans.regTalisman(["spell", "blink", 2, 80000], "Blink", "ru", function () {	});
talismans.regTalisman(["spell", "blood_of_grass", 9, 80000], "Blood of grass", "ru", function () {	});
talismans.regTalisman(["spell", "bonemeal", 9, 80000], "Bonemeal", "ru", function () {	});
// talismans.regTalisman(["spell", "build_block_relative", spiritID, 80000], "Build block relative", "ru", function () {	});
talismans.regTalisman(["spell", "build_column", 4, 80000], "Build column", "ru", function () {	});
talismans.regTalisman(["spell", "build_cylinder", 4, 80000], "Build cylinder", "ru", function () {	});
talismans.regTalisman(["spell", "build_extrusion", 4, 80000], "Build extrusion", "ru", function () {	});
talismans.regTalisman(["spell", "build_floor", 4, 80000], "Build floor", "ru", function () {	});
talismans.regTalisman(["spell", "build_from_surface", 4, 80000], "Build from surface", "ru", function () {	});
talismans.regTalisman(["spell", "build_hollow_sphere", 4, 80000], "Build hollow sphere", "ru`", function () {	});
talismans.regTalisman(["spell", "build_horizontal_line", 4, 80000], "Build horizontal line", "ru", function () {	});
talismans.regTalisman(["spell", "build_sphere", 4, 80000], "Build sphere", "ru", function () {	});
talismans.regTalisman(["spell", "build_square_floor", 4, 80000], "Build square floor", "ru", function () {	});
talismans.regTalisman(["spell", "build_square_wall", 4, 80000], "Build square wall", "ru", function () {	});
talismans.regTalisman(["spell", "build_template", 4, 80000], "Build template", "ru", function () {	});
talismans.regTalisman(["spell", "build_wall", 4, 80000], "Build wall", "ru", function () {	});
talismans.regTalisman(["spell", "clock", 6, 80000], "Clock", "ru", function () {	});
talismans.regTalisman(["spell", "combustion", 5, 80000], "Combustion", "ru", function () {	});
talismans.regTalisman(["spell", "consuming_fury", 8, 80000], "Consuming fury", "ru", function () {	});
talismans.regTalisman(["spell", "copy_area", 4, 80000], "Copy area", "ru", function () {	});
talismans.regTalisman(["spell", "copy_blocks", 4, 80000], "Copy blocks", "ru", function () {	});
talismans.regTalisman(["spell", "copy_cuboid", 4, 80000], "Copy cuboid", "ru", function () {	});
talismans.regTalisman(["spell", "crushing_palm", 7, 80000], "Crushing palm", "ru", function () {	});
talismans.regTalisman(["spell", "crystalline_road", 1, 80000], "Crystalline road", "ru", function () {	});
talismans.regTalisman(["spell", "crystallize_memory", 4, 80000], "Crystallize memory", "ru", function () {	});
talismans.regTalisman(["spell", "deserialize_memory", 4, 80000], "Deserialize memory", "ru", function () {	});
talismans.regTalisman(["spell", "destroy_cuboid_remotely", 5, 80000], "Destroy cuboid remotely", "ru", function () {	});
talismans.regTalisman(["spell", "distant_spark", 5, 80000], "Distant spark", "ru", function () {	});
talismans.regTalisman(["spell", "earthen_dive", 2, 80000], "Earthen dive", "ru", function () {	});
talismans.regTalisman(["spell", "empower_axe", 7, 80000], "Empower axe", "ru", function () {	});
talismans.regTalisman(["spell", "empower_pickaxe", 7, 80000], "Empower pickaxe", "ru", function () {	});
// talismans.regTalisman(["spell", "ender_pearl", spiritID, 80000], "Ender pearl", "ru", function () {	});
talismans.regTalisman(["spell", "escape_plan", 2, 80000], "Escape plan", "ru", function () {	});
talismans.regTalisman(["spell", "ethereal_flash", 6, 80000], "Ethereal flash", "ru", function () {	});
talismans.regTalisman(["spell", "ethereal_light", 6, 80000], "Ethereal light", "ru", function () {	});
talismans.regTalisman(["spell", "evil_eye", 3, 80000], "Evil eye", "ru", function () {	});
talismans.regTalisman(["spell", "extreme_buoyancy", 1, 80000], "Extreme buoyancy", "ru", function () {	});
talismans.regTalisman(["spell", "fall_negation", 6, 80000], "Fall negation", "ru", function () {	});
talismans.regTalisman(["spell", "fins", 1, 80000], "Fins", "ru", function () {	});
talismans.regTalisman(["spell", "flood", 1, 80000], "Flood", "ru", function () {	});
talismans.regTalisman(["spell", "focused_fury", 8, 80000], "Focused fury", "ru", function () {	});
talismans.regTalisman(["spell", "follow", 3, 80000], "Follow", "ru", function () {	});
talismans.regTalisman(["spell", "frost_wave", 1, 80000], "Frost wave", "ru", function () {	});
talismans.regTalisman(["spell", "gills", 1, 80000], "Gills", "ru", function () {	});
talismans.regTalisman(["spell", "green_cycle", 7, 80000], "Green cycle", "ru", function () {	});
talismans.regTalisman(["spell", "ground_flow", 6, 80000], "Ground flow", "ru", function () {	});
talismans.regTalisman(["spell", "grudge", 8, 80000], "Grudge", "ru", function () {	});
talismans.regTalisman(["spell", "harvest", 7, 80000], "Harvest", "ru", function () {	});
talismans.regTalisman(["spell", "heat_wave", 5, 80000], "Heat wave", "ru", function () {	});
talismans.regTalisman(["spell", "hellisphere", 5, 80000], "Hellisphere", "ru", function () {	});
talismans.regTalisman(["spell", "hovering", 6, 80000], "Hovering", "ru", function () {	});
talismans.regTalisman(["spell", "ice_bubble", 1, 80000], "Ice bubble", "ru", function () {	});
// talismans.regTalisman(["spell", "ice_carving", spiritID, 80000], "Ice carving", "ru", function () {	});
talismans.regTalisman(["spell", "ice_surface", 1, 80000], "Ice surface", "ru", function () {	});
talismans.regTalisman(["spell", "ignition", 5, 80000], "Ignition", "ru", function () {	});
talismans.regTalisman(["spell", "infernal_touch", 5, 80000], "Infernal touch", "ru", function () {	});
talismans.regTalisman(["spell", "instant_dive", 1, 80000], "Instant dive", "ru", function () {	});
talismans.regTalisman(["spell", "invite_gem", 2, 80000], "Invite gem", "ru", function () {	});
talismans.regTalisman(["spell", "invite_pebble", 2, 80000], "Invite pebble", "ru", function () {	});
talismans.regTalisman(["spell", "lake_thawing", 1, 80000], "Lake thawing", "ru", function () {	});
talismans.regTalisman(["spell", "miners_focus", 7, 80000], "Miners focus", "ru", function () {	});
talismans.regTalisman(["spell", "mist_blade", 8, 80000], "Mist blade", "ru", function () {	});
talismans.regTalisman(["spell", "molten_skin", 5, 80000], "Molten skin", "ru", function () {	});
talismans.regTalisman(["spell", "nether_surge", 5, 80000], "Nether surge", "ru", function () {	});
talismans.regTalisman(["spell", "night_eye", 3, 80000], "Night eye", "ru", function () {	});
talismans.regTalisman(["spell", "obsidian_bubble", 5, 80000], "Obsidian bubble", "ru", function () {	});
talismans.regTalisman(["spell", "obsidian_road", 1, 80000], "Obsidian road", "ru", function () {	});
// talismans.regTalisman(["spell", "overblink", spiritID, 80000], "Overblink", "ru", function () {	});
// talismans.regTalisman(["spell", "overwarp", spiritID, 80000], "Overwarp", "ru", function () {	});
talismans.regTalisman(["spell", "pearl_crumbs", 2, 80000], "Pearl crumbs", "ru", function () {	});
talismans.regTalisman(["spell", "piercing_inferno", 5, 80000], "Piercing inferno", "ru", function () {	});
talismans.regTalisman(["spell", "ping", 6, 80000], "Ping", "ru", function () {	});
talismans.regTalisman(["spell", "place_block", 4, 80000], "Place block", "ru", function () {	});
talismans.regTalisman(["spell", "place_torch", 4, 80000], "Place torch", "ru", function () {	});
talismans.regTalisman(["spell", "prismatic_eyes", 3, 80000], "Prismatic eyes", "ru", function () {	});
talismans.regTalisman(["spell", "pull_side", 4, 80000], "Pull side", "ru", function () {	});
talismans.regTalisman(["spell", "push_side", 4, 80000], "Push side", "ru", function () {	});
talismans.regTalisman(["spell", "red_pulse", 6, 80000], "Red pulse", "ru", function () {	});
talismans.regTalisman(["spell", "red_signal", 6, 80000], "Red signal", "ru", function () {	});
talismans.regTalisman(["spell", "redo", 4, 80000], "Redo", "ru", function () {	});
talismans.regTalisman(["spell", "remote_chest", 2, 80000], "Remote chest", "ru", function () {	});
talismans.regTalisman(["spell", "replace_blocks", 4, 80000], "Replace blocks", "ru", function () {	});
talismans.regTalisman(["spell", "replace_cuboid", 4, 80000], "Replace cuboid", "ru", function () {	});
talismans.regTalisman(["spell", "replace_side", 4, 80000], "Replace side", "ru", function () {	});
talismans.regTalisman(["spell", "replace_surface", 4, 80000], "Replace surface", "ru", function () {	});
talismans.regTalisman(["spell", "rotten_might", 3, 80000], "Rotten might", "ru", function () {	});
talismans.regTalisman(["spell", "searing_pulse", 5, 80000], "Searing pulse", "ru", function () {	});
talismans.regTalisman(["spell", "serialize_memory", 4, 80000], "Serialize memory", "ru", function () {	});
talismans.regTalisman(["spell", "small_fireball_throw", 5, 80000], "Small fireball throw", "ru", function () {	});
talismans.regTalisman(["spell", "snowball_throw", 1, 80000], "Snowball throw", "ru", function () {	});
talismans.regTalisman(["spell", "spider_might", 3, 80000], "Spider might", "ru", function () {	});
talismans.regTalisman(["spell", "starvation", 9, 80000], "Starvation", "ru", function () {	});
talismans.regTalisman(["spell", "stone_fever", 7, 80000], "Stone fever", "ru", function () {	});
talismans.regTalisman(["spell", "stoneball_throw", 7, 80000], "Stoneball throw", "ru", function () {	});
talismans.regTalisman(["spell", "summon_blaze", 5, 80000], "Summon blaze", "ru", function () {	});
talismans.regTalisman(["spell", "summon_cave_spider", 3, 80000], "Summon cave spider", "ru", function () {	});
talismans.regTalisman(["spell", "summon_creeper", 3, 80000], "Summon creeper", "ru", function () {	});
talismans.regTalisman(["spell", "summon_husk", 3, 80000], "Summon husk", "ru", function () {	});
talismans.regTalisman(["spell", "summon_skeleton", 3, 80000], "Summon skeleton", "ru", function () {	});
talismans.regTalisman(["spell", "summon_spider", 3, 80000], "Summon spider", "ru", function () {	});
talismans.regTalisman(["spell", "summon_stray", 3, 80000], "Summon stray", "ru", function () {	});
talismans.regTalisman(["spell", "summon_zombie", 3, 80000], "Summon zombie", "ru", function () {	});
talismans.regTalisman(["spell", "surface_blink", 2, 80000], "Surface blink", "ru", function () {	});
talismans.regTalisman(["spell", "surface_shift", 2, 80000], "Surface shift", "ru", function () {	});
talismans.regTalisman(["spell", "target", 3, 80000], "Target", "ru", function () {	});
// talismans.regTalisman(["spell", "tell_time", spiritID, 80000], "Tell time", "ru", function () {	});
talismans.regTalisman(["spell", "toadic_jump", 6, 80000], "Toadic jump", "ru", function () {	});
talismans.regTalisman(["spell", "undo", 4, 80000], "Undo", "ru", function () {	});
talismans.regTalisman(["spell", "vitalize", 1, 80000], "Vitalize", "ru", function () {	});
talismans.regTalisman(["spell", "wall_slip", 2, 80000], "Wall slip", "ru", function () {	});
talismans.regTalisman(["spell", "warp", 2, 80000], "Warp", "ru", function () {	});
talismans.regTalisman(["spell", "warp_gem", 2, 80000], "Warp gem", "ru", function () {	});
talismans.regTalisman(["spell", "warp_pebble", 2, 80000], "Warp pebble", "ru", function () {	});
talismans.regTalisman(["spell", "wild_sprint", 6, 80000], "Wild sprint", "ru", function () {	});
talismans.regTalisman(["spell", "wind_step", 6, 80000], "Wind step", "ru", function () {	});
talismans.regTalisman(["spell", "winter_breath", 1, 80000], "Winter breath", "ru", function () {	});
talismans.regTalisman(["spell", "wooden_punch", 7, 80000], "Wooden punch", "ru", function () {	});
