//{type: , texture: , spiritID: , cost}, "ru", function(){func}
talismans.regTalisman(["arrow", "anti_gravity", 0, 5], "Anti gravity arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "armor_corrosion", 9, 100], "Armor corrosion", "ru", function () {  });
talismans.regTalisman(["arrow", "blast", 5, 30], "Blast arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "blink", 2, 10], "Blink arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "climbing", 0, 10], "Climbing arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "crawling_mist", 9, 80], "Crawling mist", "ru", function () {  });
talismans.regTalisman(["arrow", "cripple", 9, 100], "Cripple", "ru", function () {  });
talismans.regTalisman(["arrow", "destructive_1", 0, 10], "Destructive arrow I", "ru", function () {  });
talismans.regTalisman(["arrow", "destructive_2", 0, 100], "Destructive arrow II", "ru", function () {  });
talismans.regTalisman(["arrow", "destructive_3", 0, 300], "Destructive arrow III", "ru", function () {  });
talismans.regTalisman(["arrow", "disarm", 0, 80], "Disarm", "ru", function () {  });
talismans.regTalisman(["arrow", "explosive", 5, 120], "Explosive arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "extinguish", 1, 10], "Extinguish fire", "ru", function () {  });
talismans.regTalisman(["arrow", "fiery_mark", 9, 120], "Fiery mark", "ru", function () {  });
talismans.regTalisman(["arrow", "fill_lungs", 9, 100], "Fill lungs", "ru", function () {  });
talismans.regTalisman(["arrow", "flak", 0, 80], "Flak arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "force", 0, 120], "", "ru", function () {  });
talismans.regTalisman(["arrow", "gamble", 0, 5], "Gamble arrow", "ru", function(){  });
talismans.regTalisman(["arrow", "hand_swap", 0, 60], "Hand swap", "ru", function () {  });
talismans.regTalisman(["arrow", "high_speed", 0, 40], "High speed arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "hollow_leg", 9, 40], "Hollow leg", "ru", function () {  });
talismans.regTalisman(["arrow", "hover_bubble", 0, 150], "Hover bubble arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "hyper_speed", 0, 400], "Hyper speed arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "ice_breaker", 1, 60], "Ice breaker", "ru", function () {  });
talismans.regTalisman(["arrow", "ice_sphere", 1, 60], "Ice sphere", "ru", function () {  });
talismans.regTalisman(["arrow", "impulse", 0, 30], "Impulse arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "incendiary", 0, 40], "Incendiary arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "life_steal", 3, 20], "Life steal arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "limp_leg", 9, 120], "Limp leg", "ru", function () {  });
talismans.regTalisman(["arrow", "lucky_arrow", 30, 30], "Lucky arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "mine", 0, 80], "Mine arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "nether", 2, 10], "Nether swap", "ru", function () {  });
talismans.regTalisman(["arrow", "nuke", 5, 400], "Nuke arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "petrification", 9, 100], "Petrification", "ru", function () {  });
talismans.regTalisman(["arrow", "piercing", 0, 40], "Piercing arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "reinforced_1", 8, 10], "Reinforced arrow I", "ru", function () {  });
talismans.regTalisman(["arrow", "reinforced_2", 8, 1000], "Reinforced arrow II", "ru", function () {  });
talismans.regTalisman(["arrow", "reinforced_3", 8, 400], "Reinforced arrow III", "ru", function () {  });
talismans.regTalisman(["arrow", "ricochet", 0, 80], "Ricochet arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "roots", 9, 80], "Roots", "ru", function () {  });
talismans.regTalisman(["arrow", "skyfall", 9, 80], "Skyfall", "ru", function () {  });
talismans.regTalisman(["arrow", "sniper", 0, 80], "Sniper arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "spooky", 3, 30], "Spooky arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "stasis", 3, 80], "Stasis arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "suffocating_fumes", 9, 100], "Suffocating fumes", "ru", function () {  });
talismans.regTalisman(["arrow", "tracer", 0, 10], "Tracer arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "vacuum", 3, 80], "Vacuum arrow", "ru", function () {  });
talismans.regTalisman(["arrow", "wind", 9, 80], "Wind leash", "ru", function () {  });
talismans.regTalisman(["arrow", "yummy", 9, 140], "Yummy smell", "ru", function () {  });
talismans.regTalisman(["arrow", "zero", 0, 30], "Zero g arrow", "ru", function(){  });