talismans.regTalisman(["blade", "blade_of_snow", 1, 5], "Blade of snow", "ru", function () {  });
talismans.regTalisman(["blade", "butchering_strike", 8, 20], "Butchering strike", "ru", function () {  });
talismans.regTalisman(["blade", "confusion", 8, 20], "Confusion", "ru", function () {  });
talismans.regTalisman(["blade", "corrosion", 8, 30], "Corrosion", "ru", function () {  });
talismans.regTalisman(["blade", "crawling_mist", 9, 80], "Crawling mist", "ru", function () {  });
talismans.regTalisman(["blade", "fiery_mark", 5, 120], "Fiery mark", "ru", function () {  });
talismans.regTalisman(["blade", "fill_lungs", 9, 100], "Fill lungs", "ru", function () {  });
talismans.regTalisman(["blade", "gamble", 8, 5], "Gamble", "ru", function () {  });
talismans.regTalisman(["blade", "hand_swap", 8, 5], "Hand swap", "ru", function () {  });
talismans.regTalisman(["blade", "heavy", 8, 30], "Heavy blade", "ru", function () {  });
talismans.regTalisman(["blade", "holy", 8, 5], "Holy blade", "ru", function () {  });
talismans.regTalisman(["blade", "hungry", 8, 10], "Hungry blade", "ru", function () {  });
talismans.regTalisman(["blade", "inflame", 5, 5], "Inflame", "ru", function () {  });
talismans.regTalisman(["blade", "lucky_strike", 8, 10], "Lucky strike", "ru", function () {  });
talismans.regTalisman(["blade", "memory", 8, 5], "Memory blade", "ru", function () {  });
talismans.regTalisman(["blade", "obliteration", 8, 5], "Obliteration", "ru", function () {  });
talismans.regTalisman(["blade", "poison_coating", 8, 5], "Poison coating", "ru", function () {  });
talismans.regTalisman(["blade", "rain_sword", 1, 5], "Rain sword", "ru", function () {  });
talismans.regTalisman(["blade", "skyfall", 9, 80], "Skyfall", "ru", function () {  });
talismans.regTalisman(["blade", "suffocating_fumes", 9, 100], "Suffocating fumes", "ru", function () {  });
talismans.regTalisman(["blade", "vengeful", 8, 5], "Vengeful blade", "ru", function () {  });
talismans.regTalisman(["blade", "wind_leash", 9, 80], "Wind leash", "ru", function () {  });
talismans.regTalisman(["blade", "wither_coating", 9, 5], "Wither coating", "ru", function () {  });
talismans.regTalisman(["blade", "yummy_smell", 9, 140], "Yummy smell", "ru", function () {  });
